// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFaqyXS-mZdkIOUUF7S8EuguCdmzEuu4Q',
    appId: '1:364804173127:android:006b40b129d135da90b062',
    messagingSenderId: '364804173127',
    projectId: 'remember-my-love',
    storageBucket: 'remember-my-love.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChASBdOfGB1cu5Er_eJYxFstFuBfyNHwY',
    appId: '1:364804173127:ios:d5ab1a5bbb5c2a7790b062',
    messagingSenderId: '364804173127',
    projectId: 'remember-my-love',
    storageBucket: 'remember-my-love.firebasestorage.app',
    androidClientId: '364804173127-k73iaegav3mg5n5fr8a62khvkdpharv7.apps.googleusercontent.com',
    iosClientId: '364804173127-ri6rj7sdlouq279a0d4sik1hgp55954u.apps.googleusercontent.com',
    iosBundleId: 'com.example.rememberMyLoveApp',
  );

}